# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Willem Yarbrough'
tagline:          '10/10 best new blog'
description:      ''
url:              http://yarbroughw.github.io
baseurl:          /

author:
  name:           'Willem Yarbrough'
  url:            https://github.com/yarbroughw

# Custom vars
version:          2.1.0

github:
repo:             https://github.com/yarbroughw/yarbroughw.github.io
